version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/DwmLutGUI"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Bucharest"
    groups:
      all-nuget:
        patterns:
          - "*"
